// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_hub_api.Data;

#nullable disable

namespace project_hub_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250408205504_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project_hub_api.Models.Projects.Notebooks.ProjectNotebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectNotebooks");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Phases.ProjectPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectPhases");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shortcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Resources.ProjectResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectResources");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectSubTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectTaskId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTaskId");

                    b.ToTable("ProjectSubTasks");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("HasSubTasks")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectPhaseId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectTaskCategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectPhaseId");

                    b.HasIndex("ProjectTaskCategoryId");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectTaskCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectPhaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectPhaseId");

                    b.ToTable("ProjectTaskCategories");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectTaskComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTaskId");

                    b.ToTable("ProjectTaskComments");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectTask_Resource", b =>
                {
                    b.Property<int>("ProjectTaskId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectResourceId")
                        .HasColumnType("int");

                    b.HasKey("ProjectTaskId", "ProjectResourceId");

                    b.HasIndex("ProjectResourceId");

                    b.ToTable("ProjectTaskResources");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.CategoryRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryRepo");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.NotebookRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotebookRepo");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.PhaseRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhaseRepo");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.ResourceRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResourceRepo");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.SubTaskRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("SubTaskRepo");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.TaskRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryRepoId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasSubTaskRepo")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhaseOrder")
                        .HasColumnType("int");

                    b.Property<int?>("TaskTypeRepoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryRepoId");

                    b.HasIndex("TaskTypeRepoId");

                    b.ToTable("TaskRepo");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.TaskRepo_ResourceRepo", b =>
                {
                    b.Property<int>("TaskRepoId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceRepoId")
                        .HasColumnType("int");

                    b.Property<string>("ResourceRepoName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskRepoId", "ResourceRepoId");

                    b.HasIndex("ResourceRepoId");

                    b.ToTable("TaskRepoResources");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.TaskTypeRepo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskTypeRepo");
                });

            modelBuilder.Entity("project_hub_api.Models.Users.ProjectRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectRoles");
                });

            modelBuilder.Entity("project_hub_api.Models.Users.ProjectUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ProjectUsers");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Notebooks.ProjectNotebook", b =>
                {
                    b.HasOne("project_hub_api.Models.Projects.Project", "Project")
                        .WithMany("ProjectNotebooks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Phases.ProjectPhase", b =>
                {
                    b.HasOne("project_hub_api.Models.Projects.Project", "Project")
                        .WithMany("ProjectPhases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Resources.ProjectResource", b =>
                {
                    b.HasOne("project_hub_api.Models.Projects.Project", "Project")
                        .WithMany("ProjectResources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_hub_api.Models.Users.ProjectUser", "User")
                        .WithMany("ProjectResources")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectSubTask", b =>
                {
                    b.HasOne("project_hub_api.Models.Projects.Tasks.ProjectTask", "ProjectTask")
                        .WithMany("ProjectSubTasks")
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectTask");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectTask", b =>
                {
                    b.HasOne("project_hub_api.Models.Projects.Phases.ProjectPhase", "ProjectPhase")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_hub_api.Models.Projects.Tasks.ProjectTaskCategory", "ProjectTaskCategory")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectTaskCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectPhase");

                    b.Navigation("ProjectTaskCategory");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectTaskCategory", b =>
                {
                    b.HasOne("project_hub_api.Models.Projects.Phases.ProjectPhase", "ProjectPhase")
                        .WithMany("ProjectTaskCategories")
                        .HasForeignKey("ProjectPhaseId");

                    b.Navigation("ProjectPhase");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectTaskComment", b =>
                {
                    b.HasOne("project_hub_api.Models.Projects.Tasks.ProjectTask", "ProjectTask")
                        .WithMany("ProjectTaskComments")
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectTask");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectTask_Resource", b =>
                {
                    b.HasOne("project_hub_api.Models.Projects.Resources.ProjectResource", "ProjectResource")
                        .WithMany("ProjectTaskResources")
                        .HasForeignKey("ProjectResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("project_hub_api.Models.Projects.Tasks.ProjectTask", "ProjectTask")
                        .WithMany("ProjectTaskResources")
                        .HasForeignKey("ProjectTaskId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProjectResource");

                    b.Navigation("ProjectTask");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.SubTaskRepo", b =>
                {
                    b.HasOne("project_hub_api.Models.Repo.TaskRepo", "Task")
                        .WithMany("SubTaskRepo")
                        .HasForeignKey("TaskId");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.TaskRepo", b =>
                {
                    b.HasOne("project_hub_api.Models.Repo.CategoryRepo", "CategoryRepo")
                        .WithMany("TaskRepo")
                        .HasForeignKey("CategoryRepoId");

                    b.HasOne("project_hub_api.Models.Repo.TaskTypeRepo", "TaskTypeRepo")
                        .WithMany("TaskRepos")
                        .HasForeignKey("TaskTypeRepoId");

                    b.Navigation("CategoryRepo");

                    b.Navigation("TaskTypeRepo");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.TaskRepo_ResourceRepo", b =>
                {
                    b.HasOne("project_hub_api.Models.Repo.ResourceRepo", "ResourceRepo")
                        .WithMany("TaskRepoResources")
                        .HasForeignKey("ResourceRepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project_hub_api.Models.Repo.TaskRepo", "TaskRepo")
                        .WithMany("TaskRepoResources")
                        .HasForeignKey("TaskRepoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceRepo");

                    b.Navigation("TaskRepo");
                });

            modelBuilder.Entity("project_hub_api.Models.Users.ProjectUser", b =>
                {
                    b.HasOne("project_hub_api.Models.Users.ProjectRole", "Role")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Phases.ProjectPhase", b =>
                {
                    b.Navigation("ProjectTaskCategories");

                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Project", b =>
                {
                    b.Navigation("ProjectNotebooks");

                    b.Navigation("ProjectPhases");

                    b.Navigation("ProjectResources");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Resources.ProjectResource", b =>
                {
                    b.Navigation("ProjectTaskResources");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectTask", b =>
                {
                    b.Navigation("ProjectSubTasks");

                    b.Navigation("ProjectTaskComments");

                    b.Navigation("ProjectTaskResources");
                });

            modelBuilder.Entity("project_hub_api.Models.Projects.Tasks.ProjectTaskCategory", b =>
                {
                    b.Navigation("ProjectTasks");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.CategoryRepo", b =>
                {
                    b.Navigation("TaskRepo");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.ResourceRepo", b =>
                {
                    b.Navigation("TaskRepoResources");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.TaskRepo", b =>
                {
                    b.Navigation("SubTaskRepo");

                    b.Navigation("TaskRepoResources");
                });

            modelBuilder.Entity("project_hub_api.Models.Repo.TaskTypeRepo", b =>
                {
                    b.Navigation("TaskRepos");
                });

            modelBuilder.Entity("project_hub_api.Models.Users.ProjectRole", b =>
                {
                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("project_hub_api.Models.Users.ProjectUser", b =>
                {
                    b.Navigation("ProjectResources");
                });
#pragma warning restore 612, 618
        }
    }
}
